package chess

enum class PieceDeplacement {
    NORTH,
    NORTH_EAST,
    EAST,
    SOUTH_EAST,
    SOUTH,
    SOUTH_WEST,
    WEST,
    NORTH_WEST,
    L_NORTH_NORTH_EAST,
    L_EAST_EAST_NORTH,
    L_EAST_EAST_SOUTH,
    L_SOUTH_SOUTH_EAST,
    L_SOUTH_SOUTH_WEST,
    L_WEST_WEST_SOUTH,
    L_WEST_WEST_NORTH,
    L_NORTH_NORTH_WEST
}